name: Test & Coverage
on: [pull_request, push]
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          bash zscripts/01-ubuntu-openblas-debian.bash
      - name: Install Rust
        run: |
          rustup toolchain install nightly --component llvm-tools-preview
          rustup default nightly
      - name: Run tests
        run: |
          RUST_BACKTRACE=1 cargo test
      - name: Install cargo-llvm-cov
        run: |
          curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
      - name: Generate code coverage
        run: |
          cargo llvm-cov --all-features --workspace --ignore-filename-regex 'build.rs|mem_check.rs|solve_matrix_market.rs' --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: lcov.info
          fail_ci_if_error: true
